### ISSUE TITLE
Media traffic not working

### ISSUE THREAD

**Issue by rishagit** [prinze77/my-app#2]
enabled websocket on asterisk and it works for signaling. But it doesn't work for media traffic. Any idea how to do it?

**Comment by chamuridis** [comment]
Try to set Protocol wss only in extension  settings 
Screenshot from freepbx, extension Tab
<img width="1747" alt="Screenshot 2023-02-20 at 7 33 10 PM" src="https://user-images.githubusercontent.com/33203521/220170737-8585a030-923b-4365-a334-d4e356de3007.png">

Check websoket messages in browser console for erros.

**Comment by rishagit** [comment]
How can i see this screen?

**Comment by chamuridis** [comment]
You need to reload the page with the network tab open F12 and filter by type 'ws'. This will show you a connection being made with a websocket. You can then click on the connection to show the traffic being sent back and forth with the server

<img width="555" alt="l6Kwf" src="https://user-images.githubusercontent.com/33203521/220178491-bfc0aa02-a895-458f-abed-bbe80580bfee.png">

**Comment by rishagit** [comment]
looks like this was an issue with my pbx setting. its working now
